[package]
name = "squareknot_graph"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.33.2", optional = true }

[features]
default = ["nalgebra"]
nalgebra = ["dep:nalgebra"]
