[package]
name = "squareknot_pathing"
version = "0.1.0"
edition = "2021"

[dependencies]
squareknot_graph = { path = "../squareknot_graph" }
squareknot_traversal = { path = "../squareknot_traversal" }